(deftheme brown
  "Brown.")

(defconst brown-theme-background "#292220")
(defconst brown-theme-foreground "grey")
(defconst brown-theme-sandy-white "#fefecf")
(defconst brown-theme-dry-green "#b5d18a")

(custom-theme-set-faces
 'brown
 `(custom-state                 ((((type x)) (:foreground "lemon chiffon"))))
 `(default                      ((((type x)) (:foreground ,brown-theme-foreground :background ,brown-theme-background))))
 `(error                        ((((type x)) (:foreground "firebrick"))))
 `(flyspell-duplicate           ((((type x)) (:foreground nil :underline t :inherit warning))))
 `(flyspell-incorrect           ((((type x)) (:foreground nil :underline t :inherit error))))
 `(font-lock-builtin-face       ((((type x)) (:foreground "light blue"))))
 `(font-lock-comment-face       ((((type x)) (:foreground "cornsilk3"))))
 `(font-lock-constant-face      ((((type x)) (:foreground "sky blue"))))
 `(font-lock-function-name-face ((((type x)) (:foreground ,brown-theme-sandy-white :inherit bold))))
 `(font-lock-keyword-face       ((((type x)) (:foreground "azure1" :inherit bold))))
 `(font-lock-string-face        ((((type x)) (:foreground "white"))))
 `(font-lock-type-face          ((((type x)) (:foreground ,brown-theme-dry-green))))
 `(font-lock-variable-name-face ((((type x)) (:foreground "cornsilk" :inherit bold))))
 `(highlight                    ((((type x)) (:foreground "cornsilk" :background nil :underline t))))
 `(isearch                      ((((type x)) (:foreground "sienna" :background "lemonchiffon"))))
 `(lazy-highlight               ((((type x)) (:background "burlywood4"))))
 `(mode-line                    ((((type x)) (:foreground "black" :background "grey75" :inverse-video nil :box nil))))
 `(region                       ((((type x)) (:background "grey22"))))
 `(term-color-black             ((((type x)) (:background ,brown-theme-background :foreground ,brown-theme-background))))
 `(term-color-blue              ((((type x)) (:background "SteelBlue3" :foreground "SteelBlue3"))))
 `(term-color-cyan              ((((type x)) (:background "light blue" :foreground "light blue"))))
 `(term-color-green             ((((type x)) (:background ,brown-theme-dry-green :foreground ,brown-theme-dry-green))))
 `(term-color-magenta           ((((type x)) (:background "light coral" :foreground "light coral"))))
 `(term-color-red               ((((type x)) (:background "firebrick" :foreground "firebrick"))))
 `(term-color-white             ((((type x)) (:background "azure1" :foreground "azure1"))))
 `(term-color-yellow            ((((type x)) (:background ,brown-theme-sandy-white :foreground ,brown-theme-sandy-white)) ))
 `(warning                      ((((type x)) (:foreground "orangered2" :bold nil))))
 `(widget-field                 ((((type x)) (:background "grey20")))))

(provide-theme 'brown)
