(deftheme sjo-color
  "Created 2014-02-11.")

(require 'derived-theme)

(derived-theme-set-faces
 'sjo-color
 'charcoal-black
 '(Info-title-1-face nil)
 '(Info-title-2-face nil)
 '(Info-title-3-face nil)
 '(Info-title-4-face nil)
 '(bold-italic ((t (:inherit (bold italic)))))
 '(cperl-array-face ((t (:inherit bold :foreground "light salmon"))))
 '(cperl-hash-face ((t (:inherit bold-italic))))
 '(custom-group-tag-face ((t (:inherit bold :foreground "pale turquoise"))))
 '(custom-variable-button-face ((t (:inherit bold :underline t))))
 '(default ((t (:background "grey7" :foreground "grey"))))
 '(display-time-mail-face nil)
 '(fixed nil)
 '(fixed-pitch nil)
 '(fringe ((t (:background "Grey10"))))
 '(gnus-article-button-face nil)
 '(gnus-article-mouse-face nil)
 '(gnus-mouse-face nil)
 '(help-highlight-face nil)
 '(info-menu-5 nil)
 '(info-menu-header ((t (:inherit (variable-pitch bold)))))
 '(info-menu-star ((t (:underline t))))
 '(info-title-1 ((t (:inherit Info-title-2-face :height 1.728))))
 '(info-title-2 ((t (:inherit Info-title-3-face :height 1.44))))
 '(info-title-3 ((t (:inherit Info-title-4-face :height 1.2))))
 '(info-title-4 ((t (:inherit (variable-pitch bold)))))
 '(isearch-lazy-highlight-face nil)
 '(italic ((t (:italic t))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(list-matching-lines-face nil)
 '(menu nil)
 '(mime-button-face nil)
 '(mime-button-mouse-face nil)
 '(mode-line ((t (:background "grey75" :foreground "black" :inverse-video nil :box nil))))
 '(org-verbatim ((t (:inherit shadow :foreground "dark orange"))))
 '(shadow ((t (:foreground "dim grey"))))
 '(show-paren-match ((t (:background "light slate blue" :foreground "white"))))
 '(show-paren-match-face nil)
 '(show-paren-mismatch ((t (:background "red" :foreground "white"))))
 '(show-paren-mismatch-face nil)
 '(term-color-black ((((type x)) (:background "Grey15" :foreground "Grey15")) (((type tty)) (:background "black" :foreground "black"))))
 '(term-color-blue ((((type x)) (:background "#438CCA" :foreground "#438CCA")) (((type tty)) (:background "blue" :foreground "blue"))))
 '(term-color-cyan ((((type x)) (:background "#00FFFF" :foreground "#00FFFF")) (((type tty)) (:background "cyan" :foreground "cyan"))))
 '(term-color-green ((((type x)) (:background "#3BB878" :foreground "#3BB878")) (((type tty)) (:background "green" :foreground "green"))))
 '(term-color-magenta ((((type x)) (:background "#F06EA9" :foreground "#F06EA9")) (((type tty)) (:background "magenta" :foreground "magenta"))))
 '(term-color-red ((((type x)) (:background "#F7977A" :foreground "#F7977A")) (((type tty)) (:background "red" :foreground "red"))))
 '(term-color-white ((((type x)) (:background "Grey" :foreground "Grey")) (((type tty)) (:background "white" :foreground "white"))))
 '(term-color-yellow ((((type x)) (:background "#FFF79A" :foreground "#FFF79A")) (((type tty)) (:background "yellow" :foreground "yellow"))))
 '(variable-pitch ((t (:family "Deja Vu Serif"))))
 '(view-highlight-face nil)
 '(widget-button ((t (:bold t :weight bold))))
 '(widget-button-face nil)
 '(widget-button-pressed ((t (:foreground "red"))))
 '(widget-button-pressed-face nil)
 '(widget-documentation ((t (:foreground "light blue"))))
 '(widget-documentation-face nil)
 '(widget-field ((t (:background "RoyalBlue4" :foreground "wheat"))))
 '(widget-field-face nil)
 '(widget-inactive ((t (:foreground "dim gray"))))
 '(widget-inactive-face nil)
 '(widget-mouse-face nil)
 '(widget-single-line-field ((t (:background "slate blue" :foreground "wheat"))))
 '(widget-single-line-field-face nil))

(derived-theme-set-variables
 'sjo-color
 'charcoal-black)

(provide-theme 'sjo-color)
