;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-hungry-delete-forward
        c-indent-line-or-region
        end-of-visual-line
        eval-and-replace
        forward-sexp
        indent-for-tab-command
        kill-region
        kmacro-end-macro
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-mark-element
        org-self-insert-command
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        eval-last-sexp
        find-tag
        list-buffers
        mouse-drag-vertical-line
        org-export
        ))
