;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        forward-sexp
        kill-region
        slime-space
        ))

(setq mc/cmds-to-run-once
      '(
        ))
