.PHONY: check-syntax
check-syntax:
	${CXX} ${CXXFLAGS} -x c++ ${CHK_SOURCES} -fsyntax-only

# case ${CHK_SOURCES} in
# 	*.c | *.h )
# 		${CC} ${CFLAGS} -x c ${CHK_SOURCES} -fsyntax-only;;
# 	*.cc | *.hh )
# 		${CXX} ${CXXFLAGS} -x c++ ${CHK_SOURCES} -fsyntax-only;;
# 	*.cu | *.cuhh )
# 		${NVCXX} ${NVCXXFLAGS} -x c++ ${CHK_SOURCES} -fsyntax-only;;
# 	*.micc | *.mich )
# 		${MICXX} ${MICXXFLAGS} -x c++ ${CHK_SOURCES} -fsyntax-only;;
# esac
